accounts/urls.py
from django.urls import path, include
from . import views
from .views import delete_lyrics
from mypage.views import user_generated_lyrics  # 다른 앱에서 뷰 import

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('mypage/', include('mypage.urls')),  # mypage 앱의 URL을 추가
    path('check_nickname/', views.check_nickname, name='check_nickname'),
    path('find_username/', views.find_username, name='find_username'),
    path('find_password/', views.find_password, name='find_password'),
    path('reset_password/<str:uid>/', views.reset_password, name='reset_password'),
    path('check_username/', views.check_username, name='check_username'),  # AJAX 용
    path('delete-lyrics/', delete_lyrics, name='delete_lyrics'),
    path('user-generated-lyrics/', user_generated_lyrics, name='user_generated_lyrics'),
    path('send_verification_code/', views.send_verification_code, name='send_verification_code'),
    path('verify_email_code/', views.verify_email_code, name='verify_email_code'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls')),            # 메인 화면
    path('lyrics/', include('lyricsgen.urls')), # 가사 생성 앱
    path('accounts/', include('accounts.urls')), # 회원가입 로그인 로그아웃
    path('mypage/', include('mypage.urls')),  # mypage 앱의 URL을 포함
    path('analyze/', include('analyze.urls')),  # analyze 앱 연결
    path('music/', include('music_search.urls')), # music_search 앱 연결
    path('recommend/', include('recommendations.urls')), # recommendations 앱연결
    path('accounts/', include('accounts.urls')),
    path('board/', include('board.urls')), #board 앱 연결
    path('support/', include('support.urls')), #고객센터


]

# 이미지(= media 파일) 접근을 가능하게 함
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path, include
from . import views
from .views import preference_view, quiz_song_view, search_results_view, results_music_info_view
from .views import preference_view, get_guguns # 메인 음악 취향 검사


urlpatterns = [
    path('', views.main, name='main'),
    path('music/', include('music_search.urls')), # music_search 앱 연결
    path('accounts/', include('accounts.urls')),  # accounts 앱의 URL을 포함시킴
    path('accounts/', include('django.contrib.auth.urls')),  # ✅ Django auth 추가
    path('lyricsgen/', include('lyricsgen.urls')),  # lyricsgen 앱의 URL을 포함시킴
    path('mypage/', include('mypage.urls')),  # mypage 앱의 URL을 포함시킴
    path('analyze/', include('analyze.urls')),  # analyze 앱 연결
    path('recommend/', include('recommendations.urls')), # recommendations 앱연결
    path('preference/', preference_view, name='preference'), # 메인 음악 취향 검사
    path("recommend_by_genre/", views.recommend_by_genre, name="recommend_by_genre"), # 메인 음악 취향 검사 추천 음악
    path('get_weather_genre/', views.get_weather_genre, name='get_weather_genre'), # 음악 취향 검사에서 날씨 조회
    path('get_guguns/', get_guguns, name='get_guguns'), # 음악 취향 검사에서 날씨 조회
    path('quiz_song/', quiz_song_view, name='quiz_song'), # 음악퀴즈
    path('search/', search_results_view, name='search_results'),#진섭이 추가
    path('music-info/', results_music_info_view, name='music_info'),#진섭이 추가
    path("check-auth/", views.check_auth, name="check_auth"),
    path("toggle-like/", views.add_or_remove_like, name="toggle_like"),
    path('board/', include('board.urls')),  # 🔥 게시판 앱 연결
    path("liked-songs-html/", views.liked_songs_html, name="liked_songs_html"),  # 0520 동건 추가 좋아요 목록 비동기 최신화
    path("lyrics-info/", views.results_music_info_view, name="results_music_info_view"), #analyze 감성 추천 곡에서 넘어오는거 # 민수가 추가함
]

accounts/models.py
# ✅ models.py
import random
import string
from django.contrib.auth.models import AbstractUser
from django.db import models

def generate_random_nickname(length=8):
    letters_and_digits = string.ascii_letters + string.digits
    return ''.join(random.choice(letters_and_digits) for _ in range(length))

class CustomUser(AbstractUser):
    nickname = models.CharField(max_length=50, unique=True, blank=True, null=True)
    birthday = models.DateField(null=True, blank=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    gender = models.CharField(
        max_length=1,
        choices=[('M', 'Male'), ('F', 'Female')],
        blank=True,
        null=True)

    profile_picture = models.CharField(
        max_length=100,
        choices=[
            ('profile1.png', '프로필1'),
            ('profile2.png', '프로필2'),
            ('profile3.png', '프로필3'),
            ('profile4.png', '프로필4'),
            ('profile5.png', '프로필5'),
        ],
        default='profile1.png'
    )

    def save(self, *args, **kwargs):
        # ✅ 닉네임이 없을 때만 자동 생성
        if not self.nickname:
            self.nickname = generate_random_nickname()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.username

accounts/forms.py
# ✅ forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from .models import CustomUser
from django.core.exceptions import ValidationError
import re

PROFILE_CHOICES = [
    ("profile1.png", "1번 이미지"),
    ("profile2.png", "2번 이미지"),
    ("profile3.png", "3번 이미지"),
    ("profile4.png", "4번 이미지"),
    ("profile5.png", "5번 이미지"),
]

GENDER_CHOICES = [
    ('M', 'Male'),
    ('F', 'Female'),
]

class CustomUserCreationForm(UserCreationForm):

    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'})) 

    gender = forms.ChoiceField(
        choices=GENDER_CHOICES,
        required=True,
        widget=forms.RadioSelect,  # 라디오 버튼으로 선택
        label="성별"
    )

    birthday = forms.DateField(
        widget=forms.SelectDateWidget(years=range(1950, 2024)),
        required=True
    )
    phone_number = forms.CharField(
        max_length=15,
        required=True,
        widget=forms.TextInput(attrs={'placeholder': '010-1234-5678'})
    )
    profile_picture = forms.ChoiceField(
        choices=PROFILE_CHOICES,
        required=False,
        label="프로필 사진 선택"
    )

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'gender','password1', 'password2', 'birthday', 'phone_number', 'profile_picture']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    def clean_phone_number(self):
        phone = self.cleaned_data.get('phone_number')
        if phone and not re.match(r'^010-\d{4}-\d{4}$', phone):
            raise ValidationError("전화번호는 010-1234-5678 형식으로 입력해주세요.")
        return phone
    
    def clean_username(self):
        username = self.cleaned_data.get('username')
        if username and len(username) < 2:
            raise ValidationError("아이디는 최소 2글자 이상이어야 합니다.")
        return username

class CustomUserChangeForm(UserChangeForm):
    nickname = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.TextInput(attrs={'placeholder': '닉네임 입력'})
    )
    birthday = forms.DateField(
        widget=forms.SelectDateWidget(years=range(1950, 2024)),
        required=True
    )
    phone_number = forms.CharField(
        max_length=15,
        required=False,
        widget=forms.TextInput(attrs={'placeholder': '010-0000-0000'})
    )
    profile_picture = forms.ChoiceField(
        choices=PROFILE_CHOICES,
        required=False,
        label="프로필 사진 선택"
    )

    class Meta:
        model = CustomUser
        fields = ['username', 'nickname', 'birthday', 'phone_number', 'profile_picture']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'password' in self.fields:
            self.fields.pop('password')

    def clean_nickname(self):
        nickname = self.cleaned_data.get('nickname')
        if not re.match(r'^[\w가-힣]+$', nickname):
            raise forms.ValidationError("닉네임은 한글, 영문, 숫자, 밑줄(_)만 사용할 수 있습니다.")
        if CustomUser.objects.exclude(pk=self.instance.pk).filter(nickname=nickname).exists():
            raise forms.ValidationError("이미 사용 중인 닉네임입니다.")
        return nickname

    def clean_phone_number(self):
        phone = self.cleaned_data.get('phone_number')
        if phone and not re.match(r'^010-\d{4}-\d{4}$', phone):
            raise ValidationError("전화번호는 010-1234-5678 형식으로 입력해주세요.")
        return phone


class CustomAuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'ID'
        self.fields['password'].label = 'PASSWORD'

    error_messages = {
        'invalid_login': "올바른 사용자 이름과 비밀번호를 입력하십시오.",
        'inactive': "이 계정은 비활성화되어 있습니다.",
    }


class PasswordResetForm(forms.Form):
    new_password = forms.CharField(widget=forms.PasswordInput, label="새 비밀번호")
    confirm_password = forms.CharField(widget=forms.PasswordInput, label="비밀번호 확인")

    def clean(self):
        cleaned_data = super().clean()
        new_pw = cleaned_data.get("new_password")
        confirm_pw = cleaned_data.get("confirm_password")

        if new_pw and confirm_pw and new_pw != confirm_pw:
            raise forms.ValidationError("비밀번호와 비밀번호 확인이 일치하지 않습니다.")
        return cleaned_data

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomAuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.http import JsonResponse
from .models import CustomUser
from django.contrib import messages # 아이디찾기
from django.contrib.auth import get_user_model # 비밀번호찾기
from django.http import HttpResponse # 비밀번호찾기
from django.contrib.auth.hashers import make_password # 비밀번호 재설정
from .forms import PasswordResetForm
from django.utils.http import url_has_allowed_host_and_scheme
from django.conf import settings
from urllib.parse import urlencode
from django.views.decorators.csrf import csrf_exempt
import json
from lyricsgen.models import GeneratedLyrics
from .utils import generate_email_code, send_email_code

def signup_view(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST,request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)  # 회원가입 후 바로 로그인
            return redirect('main')
    else:
        form = CustomUserCreationForm()
    return render(request, 'signup.html', {'form': form})


# 로그인뷰
def login_view(request):
    next_url = request.POST.get('next') or request.GET.get('next')  # ✅ GET도 체크

    if request.method == 'POST':
        form = CustomAuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect(next_url or 'main')  # ✅ next가 있으면 그곳으로 이동
    else:
        form = CustomAuthenticationForm()

    return render(request, 'login.html', {'form': form, 'next': next_url})

# 로그아웃 뷰
def logout_view(request):
    next_url = request.GET.get('next') or request.META.get('HTTP_REFERER') or 'main'
    logout(request)
    return redirect(next_url)

def check_nickname(request):
    nickname = request.GET.get('nickname')
    current_user_id = request.user.id
    exists = CustomUser.objects.exclude(pk=current_user_id).filter(nickname=nickname).exists()
    return JsonResponse({'duplicate': exists})

# 아이디찾기
def find_username(request):
    if request.method == 'POST':
        phone = request.POST.get('phone')
        user = CustomUser.objects.filter(phone_number=phone).first()
        if user:
            return render(request, 'found_username.html', {'username': user.username})
        else:
            messages.error(request, '일치하는 사용자가 없습니다.')
    return render(request, 'find_username.html')

# 비밀번호찾기
def find_password(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        phone = request.POST.get('phone_number')
        try:
            user = CustomUser.objects.get(username=username, phone_number=phone)
            return redirect('reset_password', uid=user.username)
        except CustomUser.DoesNotExist:
            messages.error(request, '일치하는 사용자 정보가 없습니다.')
    return render(request, 'find_password.html')

def reset_password(request, uid):
    try:
        user = CustomUser.objects.get(username=uid)
    except CustomUser.DoesNotExist:
        messages.error(request, '유효하지 않은 접근입니다.')
        return redirect('find_password')

    if request.method == 'POST':
        form = PasswordResetForm(request.POST)
        if form.is_valid():
            new_pw = form.cleaned_data['new_password']
            user.password = make_password(new_pw)
            user.save()
            messages.success(request, '비밀번호가 재설정되었습니다.')
            return redirect('login')
        else:
            messages.error(request, '비밀번호가 일치하지 않습니다.')  # ❗ 안내문구
    else:
        form = PasswordResetForm()

    return render(request, 'reset_password.html', {'form': form, 'username': uid})

User = get_user_model()

def check_username(request):
    username = request.GET.get("username", "")
    exists = User.objects.filter(username=username).exists()  # ✅ 정확히 일치하는지만 검사
    return JsonResponse({'available': not exists})


@csrf_exempt
def delete_lyrics(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            ids = data.get('ids', [])
            if not ids:
                return JsonResponse({'success': False, 'error': 'No IDs provided'})

            GeneratedLyrics.objects.filter(id__in=ids).delete()
            return JsonResponse({'success': True})
        except Exception as e:
            return JsonResponse({'success': False, 'error': str(e)})
    return JsonResponse({'success': False, 'error': 'Invalid method'}, status=400)

# 인증번호 발송
@csrf_exempt
def send_verification_code(request):
    if request.method == "POST":
        email = request.POST.get('email')
        if not email:
            return JsonResponse({'success': False, 'error': '이메일을 입력하세요.'})
        code = generate_email_code()
        request.session['email_verification_code'] = code
        request.session['email_for_verification'] = email
        send_email_code(email, code)
        return JsonResponse({'success': True})
    return JsonResponse({'success': False, 'error': '잘못된 요청입니다.'})

# 인증번호 검증
@csrf_exempt
def verify_email_code(request):
    if request.method == "POST":
        input_code = request.POST.get('code')
        saved_code = request.session.get('email_verification_code')
        if input_code == saved_code:
            return JsonResponse({'verified': True})
        else:
            return JsonResponse({'verified': False})
    return JsonResponse({'verified': False, 'error': '잘못된 요청입니다.'})

# 회원가입 최종 처리 시 이메일 인증 확인
def signup_view(request):
    if request.method == 'POST':
        if not request.session.get('email_verification_code'):
            messages.error(request, '이메일 인증을 완료해주세요.')
            form = CustomUserCreationForm(request.POST, request.FILES)
            return render(request, 'signup.html', {'form': form})

        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('main')
    else:
        form = CustomUserCreationForm()
    return render(request, 'signup.html', {'form': form})

accounts/templates/find_password.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Find Username{% endblock %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<link rel="stylesheet" href="{% static 'css/find_username.css' %}">
{% endblock %}

{% block content %}
<div class="login-container">
  <div class="login-form">
    <form method="POST">
      <h1>FIND USERNAME</h1>
        {% csrf_token %}

        <label for="username">ID</label>
        <input type="text" name="username" id="username" required>

        <!-- 전화번호 입력 -->
        <label for="phone">Phone Number</label>
        <input type="text" name="phone" id="phone" placeholder="010-0000-0000" required>

        <!-- 이메일 입력 -->
        <label for="email">Email</label>
        <input type="email" name="email" id="email" placeholder="example@example.com" required>

        <!-- 이메일 인증번호 입력줄 -->
        <div class="inline-input-row">
          <input type="text" name="email_code" id="email-code-input" placeholder="Enter verification code" maxlength="6" required>
          <button type="button" id="send-code-btn">Send</button>
        </div>

        <!-- 이메일 인증 메시지 -->
        <span id="email-verify-msg" class="check-msg"></span>

        {% if messages %}
          {% for message in messages %}
            <p class="error-msg">{{ message }}</p>
          {% endfor %}
        {% endif %}

        <!-- 찾기 버튼 -->
        <button class="sign font_color" type="submit">Find Username</button>
      </form>
      <span>
          Did you remember your ID?
          <a class="btn-glitch" href="{% url 'login' %}" style="color: rgba(167, 167, 156, 0.897)">Sign in</a>
        </span>
{% endblock %}
{% block extra_script %}
<script src="{% static 'js/base.js' %}"></script>
<script src="{% static 'js/find_username.js' %}"></script>
{% endblock %}

accounts/templates/find_username.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Find Username{% endblock %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<link rel="stylesheet" href="{% static 'css/find_username.css' %}">
{% endblock %}

{% block content %}
<div class="login-container">
  <div class="login-form">
    <h1>FIND USERNAME</h1>
    <form method="POST">
      {% csrf_token %}

      <!-- 전화번호 입력 -->
      <label for="phone">Phone Number</label>
      <input type="text" name="phone" id="phone" placeholder="010-0000-0000" required>

      <!-- 이메일 입력 -->
      <label for="email">Email</label>
      <input type="email" name="email" id="email" placeholder="example@example.com" required>

      <!-- 이메일 인증번호 입력줄 -->
      <div class="inline-input-row">
        <input type="text" name="email_code" id="email-code-input" placeholder="Enter verification code" maxlength="6" required>
        <button type="button" id="send-code-btn">Send</button>
      </div>

      <!-- 이메일 인증 메시지 -->
      <span id="email-verify-msg" class="check-msg"></span>

      {% if messages %}
        {% for message in messages %}
          <p class="error-msg">{{ message }}</p>
        {% endfor %}
      {% endif %}

      <!-- 찾기 버튼 -->
      <button class="sign font_color" type="submit">Find Username</button>
    </form>
{% endblock %}
{% block extra_script %}
<script src="{% static 'js/base.js' %}"></script>
<script src="{% static 'js/find_username.js' %}"></script>
{% endblock %}

accounts/templates/found_username.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Found_username{% endblock %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<style>
  .login-form p {
    margin-bottom: 30px;  /* ✅ 결과와 버튼 사이 여백 추가 */
  }
</style>
{% endblock %}

{% block content %}
<div class="login-container">
  <div class="login-form">
    <h1>Username Found</h1>

    <p>당신의 아이디는 <strong>{{ username }}</strong> 입니다.</p>
    <a class="btn-glitch" href="{% url 'login' %}">로그인 하러 가기</a>
  </div>
</div>
{% endblock %}

{% block extra_script %}
<script src="{% static 'js/base.js' %}"></script>
{% endblock %}

accounts/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Login{% endblock %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block content %}
<div class="login-container">
  <div class="login-form">
    <h1>SIGN IN</h1>
    <form method="POST" action="{% url 'login' %}">
      {% csrf_token %}
      <input type="hidden" name="next" value="{{ next }}">

      {% if form.non_field_errors %}
        <ul class="errorlist">
          {% for error in form.non_field_errors %}
            <li>{{ error }}</li>
          {% endfor %}
        </ul>
      {% endif %}

      <div class="form-group">
        <label for="{{ form.username.id_for_label }}">ID</label>
        {{ form.username }}
        {% if form.username.errors %}
          <ul class="errorlist">
            {% for error in form.username.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>

      <div class="form-group">
        <label for="{{ form.password.id_for_label }}">PASSWORD</label>
        {{ form.password }}
        {% if form.password.errors %}
          <ul class="errorlist">
            {% for error in form.password.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </div>

      <button class="sign font_color" type="submit">SIGN IN</button>
    </form>

    <div class="account-links">
      <a class="btn-glitch font_color" href="{% url 'find_username' %}">Find Username</a>
      <a class="btn-glitch font_color" href="{% url 'find_password' %}">Find Password</a>
    </div>

    <span class="signup ">Not registered yet? <a class="btn-glitch font_color" href="{% url 'signup' %}">SIGN UP</a></span>
  </div>
</div>
{% endblock %}

{% block extra_script %}
<script src="{% static 'js/base.js' %}"></script>
{% endblock %}

accounts/templates/reset_password.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Reset_password{% endblock %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/main.css' %}">
{% endblock %}

{% block content %}
<div class="login-container">
  <div class="login-form">
    <h1>RESET PASSWORD</h1>

    {% if messages %}
      {% for message in messages %}
        <p style="color: red;">{{ message }}</p>
      {% endfor %}
    {% endif %}

    <form method="POST">
      {% csrf_token %}
      {{ form.non_field_errors }}
      
      <label for="{{ form.new_password.id_for_label }}" style="color: white;">{{ form.new_password.label }}</label>
      {{ form.new_password }}

      <label for="{{ form.confirm_password.id_for_label }}" style="color: white;">{{ form.confirm_password.label }}</label>
      {{ form.confirm_password }}

      <button class="btn-glitch" type="submit">비밀번호 변경</button>
    </form>

    <span><a class="btn-glitch" href="{% url 'login' %}">로그인 하러 가기</a></span>
  </div>
</div>
{% endblock %}

{% block extra_script %}
<script src="{% static 'js/base.js' %}"></script>
{% endblock %}

accounts/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Signup{% endblock %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<link rel="stylesheet" href="{% static 'css/signup.css' %}">
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block content %}
<div class="signup-container">
  <div class="signup-form">
    <h1>SIGN UP</h1>
    <form class="signup-content" method="POST" enctype="multipart/form-data">
      {% csrf_token %}

      <!-- ID -->
      <p>
        <label for="id_username">ID</label>
        {{ form.username }}
      <ul class="input-info">
        <li>영문, 숫자, @/./+/-/_ 가능</li>
        <li>중복 불가, 최소 2자, 최대 150자</li>
      </ul>
      <span id="username-check" class="check-msg"></span>
      </p>

      <!-- Password -->
      <p>
        <label for="id_password1">Password</label>
        {{ form.password1 }}
      <ul class="input-info">
        <li>8자 이상</li>
        <li>숫자만 사용 불가</li>
      </ul>
      <span id="password-check" class="check-msg"></span>
      </p>
      <p>
        <label for="id_password2">Confirm Password</label>
        {{ form.password2 }}
      </p>

      <!-- Email -->
      <p>
        <label for="id_email">Email</label>
        <span class="inline-input-row">
          <input type="email" id="id_email" name="email" required placeholder="예: user@example.com">
          <button type="button" id="send-code-btn">Send</button>
        </span>
        <span id="email-send-msg" class="check-msg "></span>
      </p>

      <!-- 인증번호 입력 -->
      <p>
        <label for="email-code-input">Enter verification code</label>
        <span class="inline-input-row">
          <input type="text" id="email-code-input" name="email_code" maxlength="6">
          <button type="button" id="verify-code-btn">Verify</button>
        </span>
        <span id="email-verify-msg" class="check-msg"></span>
      </p>


      <!-- Birthday -->
      <p>
        <label for="id_birthday">Birthday</label>
        {{ form.birthday }}
      </p>

      <!-- Gender -->
      <p>
        <label for="id_gender">Gender</label>
        {{ form.gender }}
      </p>

      <!-- Phone Number -->
      <p>
        <label for="id_phone_number">Phone Number</label>
        {{ form.phone_number }}
        <span id="phone-check" class="check-msg"></span> <!-- ✅ 추가 -->
      </p>

      <!-- Profile Picture -->
      <p>
        <label>Profile Picture</label>
      </p>
      <div class="profile-icon-selector">
        <div class="icon-option" data-value="profile1.png">
          <img src="{% static 'images/profiles/profile1.png' %}" alt="Icon 1">
        </div>
        <div class="icon-option" data-value="profile2.png">
          <img src="{% static 'images/profiles/profile2.png' %}" alt="Icon 2">
        </div>
        <div class="icon-option" data-value="profile3.png">
          <img src="{% static 'images/profiles/profile3.png' %}" alt="Icon 3">
        </div>
        <div class="icon-option" data-value="profile4.png">
          <img src="{% static 'images/profiles/profile4.png' %}" alt="Icon 4">
        </div>
        <div class="icon-option" data-value="profile5.png">
          <img src="{% static 'images/profiles/profile5.png' %}" alt="Icon 5">
        </div>
        <input type="hidden" name="profile_picture" id="selected-profile-picture" value="">
      </div>

      <button class="sign" type="submit">SIGN UP</button>
    </form>
  </div>
</div>
{% endblock %}

{% block extra_script %}
<script src="{% static 'js/base.js' %}"></script>
<script src="{% static 'js/signup.js' %}"></script>
{% endblock %}